
spring:
  cloud:
    stream:
      bindings:
        responseData-in-0:
          destination: test-kinesis-henry-y-lee-stream

cloud:
  aws:
    region:
      static: ap-northeast-1
    stack:
      auto: false
    credentials:
      profile-name: default
