spring:

  profiles:
    active:"@activeProfile@"

  cloud:
    stream:
      bindings:
        responseData-in-0:
          destination: test-kinesis-henry-y-lee-stream

cloud:
  aws:
    credentials:
      profile-name: default
    region:
      static: ap-northeast-1
    stack:
      auto: false