spring:
  cloud:
    stream:
      bindings:
        source-out-0:
          destination: test-kinesis-henry-y-lee-stream

cloud:
  aws:
    region:
      static: ap-northeast-1
    stack:
      auto: false